package entities;
// Generated 2 juil. 2019 15:22:49 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Achats generated by hbm2java
 */
@Entity
@Table(name = "achats", catalog = "g_stock")
public class Achats implements java.io.Serializable {

	private Integer codeAchat;
	private int codeArt;
	private int qteAchete;
	private Date dateReception;

	public Achats() {
	}

	public Achats(int codeArt, int qteAchete, Date dateReception) {
		this.codeArt = codeArt;
		this.qteAchete = qteAchete;
		this.dateReception = dateReception;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "codeAchat", unique = true, nullable = false)
	public Integer getCodeAchat() {
		return this.codeAchat;
	}

	public void setCodeAchat(Integer codeAchat) {
		this.codeAchat = codeAchat;
	}

	@Column(name = "codeArt", nullable = false)
	public int getCodeArt() {
		return this.codeArt;
	}

	public void setCodeArt(int codeArt) {
		this.codeArt = codeArt;
	}

	@Column(name = "qteAchete", nullable = false)
	public int getQteAchete() {
		return this.qteAchete;
	}

	public void setQteAchete(int qteAchete) {
		this.qteAchete = qteAchete;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateReception", nullable = false, length = 10)
	public Date getDateReception() {
		return this.dateReception;
	}

	public void setDateReception(Date dateReception) {
		this.dateReception = dateReception;
	}

}
