package entities;
// Generated 26 juin 2019 18:03:01 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Articles generated by hbm2java
 */
@Entity
@Table(name = "articles", catalog = "g_vente")
public class Articles implements java.io.Serializable {

	private int codeArt;
	private String nomArt;
	private String descArt;
	private int prixArt;

	public Articles() {
	}

	public Articles(int codeArt, String nomArt, String descArt, int prixArt) {
		this.codeArt = codeArt;
		this.nomArt = nomArt;
		this.descArt = descArt;
		this.prixArt = prixArt;
	}

	@Id

	@Column(name = "codeArt", unique = true, nullable = false)
	public int getCodeArt() {
		return this.codeArt;
	}

	public void setCodeArt(int codeArt) {
		this.codeArt = codeArt;
	}

	@Column(name = "nomArt", nullable = false, length = 20)
	public String getNomArt() {
		return this.nomArt;
	}

	public void setNomArt(String nomArt) {
		this.nomArt = nomArt;
	}

	@Column(name = "descArt", nullable = false, length = 200)
	public String getDescArt() {
		return this.descArt;
	}

	public void setDescArt(String descArt) {
		this.descArt = descArt;
	}

	@Column(name = "prixArt", nullable = false)
	public int getPrixArt() {
		return this.prixArt;
	}

	public void setPrixArt(int prixArt) {
		this.prixArt = prixArt;
	}

}
