package entities;
// Generated 2 juil. 2019 15:22:49 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Inventaire generated by hbm2java
 */
@Entity
@Table(name = "inventaire", catalog = "g_stock")
public class Inventaire implements java.io.Serializable {

	private Integer codeInv;
	private int codeArt;
	private int qteArt;
	private String descInv;
	private Date dateInv;

	public Inventaire() {
	}

	public Inventaire(int codeArt, int qteArt, String descInv, Date dateInv) {
		this.codeArt = codeArt;
		this.qteArt = qteArt;
		this.descInv = descInv;
		this.dateInv = dateInv;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "codeInv", unique = true, nullable = false)
	public Integer getCodeInv() {
		return this.codeInv;
	}

	public void setCodeInv(Integer codeInv) {
		this.codeInv = codeInv;
	}

	@Column(name = "codeArt", nullable = false)
	public int getCodeArt() {
		return this.codeArt;
	}

	public void setCodeArt(int codeArt) {
		this.codeArt = codeArt;
	}

	@Column(name = "qteArt", nullable = false)
	public int getQteArt() {
		return this.qteArt;
	}

	public void setQteArt(int qteArt) {
		this.qteArt = qteArt;
	}

	@Column(name = "descInv", nullable = false, length = 200)
	public String getDescInv() {
		return this.descInv;
	}

	public void setDescInv(String descInv) {
		this.descInv = descInv;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateInv", nullable = false, length = 10)
	public Date getDateInv() {
		return this.dateInv;
	}

	public void setDateInv(Date dateInv) {
		this.dateInv = dateInv;
	}

}
